services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - ./backend/app:/app/app
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    command: >
      sh -c "uv run alembic upgrade head && 
             uv run uvicorn app.entrypoints.__main__:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload"

  postgres:
    image: postgres:16-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: