services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://${APP_DOMAIN}/api/v1
    restart: unless-stopped
    env_file: .env
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}"
    networks:
      - app-network
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - ./backend/app:/app/app
    ports:
      - "${BACKEND_PORT}"
    networks:
      - app-network

  tgbot:
    build:
      context: ./tgbot
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    depends_on:
      - backend
    volumes:
      - ./tgbot/app:/app/app
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  certbot-init:
    image: certbot/certbot
    entrypoint: /bin/sh
    command: -c 'test -d /etc/letsencrypt/live/${APP_DOMAIN} || certbot certonly -v --standalone -v -d $APP_DOMAIN -m $LETSENCRYPT_EMAIL --force-renewal --agree-tos || true'
    volumes:
      - cert_volume:/etc/letsencrypt

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      BACKEND_PORT: ${BACKEND_PORT}
      FRONTEND_PORT: ${FRONTEND_PORT}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - cert_volume:/etc/letsencrypt
      - acme_challenge:/usr/share/nginx/html/.well-known
    depends_on:
      certbot-init:
          condition: service_completed_successfully
    networks:
      - app-network
    env_file:
      - .env

  certbot:
    image: certbot/certbot
    entrypoint: /bin/sh
    command: -c 'trap exit TERM; while :; do certbot renew; sleep 24h && wait $${!}; done;'
    depends_on:
      nginx:
        condition: service_started
    volumes:
      - cert_volume:/etc/letsencrypt
      - acme_challenge:/usr/share/nginx/html/.well-known

volumes:
  rabbitmq_data:
  postgres_data:
  cert_volume:
  acme_challenge:

networks:
  app-network:
    driver: bridge