"""daily_number in order

Revision ID: 372a2ae04c03
Revises: 9fcd4d707e84
Create Date: 2026-03-27 02:07:33.075772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372a2ae04c03'
down_revision: Union[str, Sequence[str], None] = '9fcd4d707e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_daily_counter',
    sa.Column('counter_date', sa.Date(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('counter_date')
    )
    op.add_column('orders', sa.Column('daily_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'daily_number')
    op.drop_table('order_daily_counter')
    # ### end Alembic commands ###
