"""bowl added price, bowl added price evening

Revision ID: 480ff6d4cc98
Revises: 891f48b2f428
Create Date: 2026-04-08 19:37:32.235915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480ff6d4cc98'
down_revision: Union[str, Sequence[str], None] = '891f48b2f428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bowls', sa.Column('added_price', sa.Float(), nullable=False, server_default=sa.text("0")))
    op.add_column('bowls', sa.Column('added_price_evening', sa.Float(), nullable=False, server_default=sa.text("0")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bowls', 'added_price_evening')
    op.drop_column('bowls', 'added_price')
    # ### end Alembic commands ###
