"""priority is a number instead of a date

Revision ID: 49b823c95335
Revises: 83dbe079a88d
Create Date: 2026-04-04 19:45:44.932899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49b823c95335'
down_revision: Union[str, Sequence[str], None] = '83dbe079a88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flavors', sa.Column('priority', sa.Integer(), nullable=True))
    op.drop_column('flavors', 'priority_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flavors', sa.Column('priority_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('flavors', 'priority')
    # ### end Alembic commands ###
