"""strength in preset

Revision ID: 4e6111087ab6
Revises: 79c86f44bc7a
Create Date: 2026-03-24 20:43:38.524444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6111087ab6'
down_revision: Union[str, Sequence[str], None] = '79c86f44bc7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presets', sa.Column('strength', sa.Integer(), nullable=False, server_default=sa.text("1")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presets', 'strength')
    # ### end Alembic commands ###
