"""description in flavor

Revision ID: 51d265845f98
Revises: 4e6111087ab6
Create Date: 2026-03-25 22:51:33.193274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d265845f98'
down_revision: Union[str, Sequence[str], None] = '4e6111087ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flavors', sa.Column('description', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flavors', 'description')
    # ### end Alembic commands ###
