"""preset created_by_admin

Revision ID: 7195dfd58d14
Revises: 480ff6d4cc98
Create Date: 2026-04-09 21:32:48.051239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7195dfd58d14'
down_revision: Union[str, Sequence[str], None] = '480ff6d4cc98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('preset_flavors_flavor_id_fkey'), 'preset_flavors', type_='foreignkey')
    op.drop_constraint(op.f('preset_flavors_preset_id_fkey'), 'preset_flavors', type_='foreignkey')
    op.create_foreign_key(None, 'preset_flavors', 'flavors', ['flavor_id'], ['id'])
    op.create_foreign_key(None, 'preset_flavors', 'presets', ['preset_id'], ['id'])
    op.add_column('presets', sa.Column('created_by_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presets', 'created_by_admin')
    op.drop_constraint(None, 'preset_flavors', type_='foreignkey')
    op.drop_constraint(None, 'preset_flavors', type_='foreignkey')
    op.create_foreign_key(op.f('preset_flavors_preset_id_fkey'), 'preset_flavors', 'presets', ['preset_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('preset_flavors_flavor_id_fkey'), 'preset_flavors', 'flavors', ['flavor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
