"""links for suggestions in settings

Revision ID: 7688747d69b3
Revises: 49b823c95335
Create Date: 2026-04-04 20:19:40.263744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7688747d69b3'
down_revision: Union[str, Sequence[str], None] = '49b823c95335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('liquids_image_url', sa.String(length=255), nullable=True))
    op.add_column('settings', sa.Column('bowls_image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'bowls_image_url')
    op.drop_column('settings', 'liquids_image_url')
    # ### end Alembic commands ###
