"""order in flavor category

Revision ID: 83dbe079a88d
Revises: f961cedd2da2
Create Date: 2026-04-04 04:19:57.774099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83dbe079a88d'
down_revision: Union[str, Sequence[str], None] = 'f961cedd2da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flavor_categories', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flavor_categories', 'order')
    # ### end Alembic commands ###
