"""bowl added image_url

Revision ID: 864ce4e130b6
Revises: 7195dfd58d14
Create Date: 2026-04-11 11:17:21.922708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '864ce4e130b6'
down_revision: Union[str, Sequence[str], None] = '7195dfd58d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bowls', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('preset_flavors_preset_id_fkey'), 'preset_flavors', type_='foreignkey')
    op.drop_constraint(op.f('preset_flavors_flavor_id_fkey'), 'preset_flavors', type_='foreignkey')
    op.create_foreign_key(None, 'preset_flavors', 'flavors', ['flavor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'preset_flavors', 'presets', ['preset_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'preset_flavors', type_='foreignkey')
    op.drop_constraint(None, 'preset_flavors', type_='foreignkey')
    op.create_foreign_key(op.f('preset_flavors_flavor_id_fkey'), 'preset_flavors', 'flavors', ['flavor_id'], ['id'])
    op.create_foreign_key(op.f('preset_flavors_preset_id_fkey'), 'preset_flavors', 'presets', ['preset_id'], ['id'])
    op.drop_column('bowls', 'image_url')
    # ### end Alembic commands ###
