"""user phone number and personal preset base price, preset base price evening

Revision ID: 891f48b2f428
Revises: 7688747d69b3
Create Date: 2026-04-05 23:42:24.920394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891f48b2f428'
down_revision: Union[str, Sequence[str], None] = '7688747d69b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('preset_base_price_evening', sa.Float(), nullable=False, server_default=sa.text('0')))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('preset_base_price', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'preset_base_price')
    op.drop_column('users', 'phone_number')
    op.drop_column('settings', 'preset_base_price_evening')
    # ### end Alembic commands ###
