"""strength_added_price in settings

Revision ID: 9fcd4d707e84
Revises: 51d265845f98
Create Date: 2026-03-26 00:40:21.960267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fcd4d707e84'
down_revision: Union[str, Sequence[str], None] = '51d265845f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('strength_added_price', sa.Float(), nullable=False, server_default=sa.text("0")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'strength_added_price')
    # ### end Alembic commands ###
