"""many categories in flavor

Revision ID: d75223e28ef6
Revises: 372a2ae04c03
Create Date: 2026-04-02 21:08:25.366982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd75223e28ef6'
down_revision: Union[str, Sequence[str], None] = '372a2ae04c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flavor_categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('flavor_categories_association',
    sa.Column('flavor_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['flavor_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flavor_id'], ['flavors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('flavor_id', 'category_id')
    )
    op.drop_column('flavors', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flavors', sa.Column('category', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_table('flavor_categories_association')
    op.drop_table('flavor_categories')
    # ### end Alembic commands ###
