"""added is_available to DBPreset

Revision ID: ee55b1504e70
Revises: 5cb56666aac8
Create Date: 2026-02-22 22:27:12.718379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee55b1504e70'
down_revision: Union[str, Sequence[str], None] = '5cb56666aac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presets', sa.Column('is_available', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presets', 'is_available')
    # ### end Alembic commands ###
