"""priority datetime in flavor

Revision ID: f961cedd2da2
Revises: d75223e28ef6
Create Date: 2026-04-04 00:55:36.685958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f961cedd2da2'
down_revision: Union[str, Sequence[str], None] = 'd75223e28ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flavors', sa.Column('priority_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flavors', 'priority_at')
    # ### end Alembic commands ###
